export const ADD_PERSON_START = 'ADD_PERSON_START';
export const ADD_PERSON_SUCCESS = 'ADD_PERSON_SUCCESS';
export const ADD_PERSON_FAIL = 'ADD_PERSON_FAIL';
export const DELETE_PERSON_START = 'DELETE_PERSON_START';
export const DELETE_PERSON_FAIL = 'DELETE_PERSON_FAIL';
export const UPDATE_PERSON_START = 'UPDATE_PERSON_START';
export const UPDATE_PERSON_LOCAL = 'UPDATE_PERSON_LOCAL';
export const UPDATE_PERSON_SUCCESS = 'UPDATE_PERSON_SUCCESS';
export const UPDATE_PERSON_FAIL = 'UPDATE_PERSON_FAIL';

export const ADD_EXPENSE_START = 'ADD_EXPENSE_START';
export const ADD_EXPENSE_FAIL = 'ADD_EXPENSE_FAIL';
export const DELETE_EXPENSE_START = 'DELETE_EXPENSE_START'
export const DELETE_EXPENSE_FAIL = 'DELETE_EXPENSE_FAIL'
export const EDIT_EXPENSE_START = 'EDIT_EXPENSE_START'
export const EDIT_EXPENSE_FAIL = 'EDIT_EXPENSE_FAIL'

export const SET_EVENT = 'SET_EVENT';
export const CLEAN_EVENT = 'CLEAN_EVENT';

export const FOCUS_EDIT_EVENT_NAME = 'FOCUS_EDIT_EVENT_NAME'

export const OPEN_PERSON_MODAL = 'OPEN_PERSON_MODAL'
export const CLOSE_PERSON_MODAL = 'CLOSE_PERSON_MODAL'

export const UPDATE_EVENT_NAME = 'UPDATE_EVENT_NAME'
export const UPDATE_EVENT_NAME_FAIL = 'UPDATE_EVENT_NAME_FAIL';
export const SET_EXAMPLE_EVENT = 'SET_EXAMPLE_EVENT' //This is used at the example event

export const SET_TITLE = 'SET_TITLE'
export const RESET_NAVBAR = 'RESET_NAVBAR'
export const SET_BACK_ARROW = 'SET_BACK_ARROW'
export const SAVE_FORM = 'SAVE_FORM'